
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: feskMysqlDB
    environment:
     - MYSQL_ROOT_PASSWORD=feskMysqlDB
     - MYSQL_DATABASE=feskMysqlDB
    ports:
      - "3306:3306"
    volumes:
      - ./feskMysqlDB/db:/var/lib/mysql
    networks:
      - net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - net
    ports:
      - 9090:9090
      
  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./tempo.yaml:/etc/tempo.yaml"
    ports:
      - "3200:3200" # Tempo
      - "9411:9411" # zipkin
    networks:
      - net
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - net
    
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - net
    
volumes:
  grafana-storage: {}

networks:
  net:
    driver: bridge

